name: Deploy to Staging
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.DEPLOYMENT_TOKEN }}
          deploy-branch: gh-pages
  uploadToStaging:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: Checkout gh-pages
      uses: actions/checkout@v1
      with:
        ref: 'gh-pages'
    - name: FTP to staging
      uses: sebastianpopp/git-ftp-action@releases/v3
      with:
        url: ${{ secrets.ftpserver }}
        user: ${{ secrets.stagingftpuser }}
        password: ${{ secrets.stagingftppassword }}
        options: --auto-init --force --verbose --insecure --all
